export const ADDTION_OPERATION = "ADDTION_OPERATION";
export const SUBTRACTION_OPERATION = "SUBTRACTION_OPERATION";
export const LOCAL_STORAGE_COMPARE_PRODUCT_IDS =
    "LOCAL_STORAGE_COMPARE_PRODUCT_IDS";
export const LOCAL_STORAGE_PRODUCT_IN_CART = "LOCAL_STORAGE_PRODUCT_IN_CART";
